version: '3.9'

services:
  vector:
    image: docker.io/timberio/vector:0.38.0-alpine
    restart: on-failure
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
      - /var/log/:/var/log
      # - ./collector/agent/vector.yaml:/etc/vector/vector.yaml:ro
      - ./collector/vector.yaml:/etc/vector/vector.yaml:ro
    user: root
    # ports:
    #   - '8686:8686'
    networks:
      - vlogs
    depends_on:
      victorialogs:
        condition: service_healthy
      victoriametrics:
        condition: service_healthy
  
  aggregator:
    image: docker.io/timberio/vector:0.38.0-alpine
    restart: on-failure
    volumes:
      - ./collector/aggregator/vector.yaml:/etc/vector/vector.yaml:ro
    user: root
    networks:
      - vlogs
    depends_on:
      victorialogs:
        condition: service_healthy
      victoriametrics:
        condition: service_healthy
  
  grafana:
    # image: grafana/grafana-enterprise
    build:
      context: .
      dockerfile: grafana/Dockerfile
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: victorialogs-datasource,victoriametrics-datasource
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.example.com`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks:
      - vlogs
    ports:
     - '127.0.0.1:3000:3000'
  grafana_2:
    image: grafana/grafana:11.0.0
    environment:
    - GF_INSTALL_PLUGINS=https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v0.4.0/victorialogs-datasource-v0.4.0.zip;victorialogs-datasource
    - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=victorialogs-datasource
    ports:
    - 3001:3000/tcp
    networks:
      - vlogs

  victorialogs:
    image: docker.io/victoriametrics/victoria-logs:v0.5.2-victorialogs
    volumes:
      - victorialogs-vector-docker-vl:/vlogs
    ports:
      - '127.0.0.1:9428:9428'
    command:
      - -storageDataPath=/vlogs
      - -loggerFormat=json
      - -retentionPeriod=2y
      - -pushmetrics.extraLabel='instance=victorialogs'
      # - -httpAuth.username=admin
      # - -httpAuth.password=password
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.victorialogs.rule=Host(`victorialogs.example.com`)"
      - "traefik.http.routers.victorialogs.entrypoints=websecure"
      - "traefik.http.routers.victorialogs.service=victorialogs"
      - "traefik.http.routers.victorialogs.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=test:$$apr1$$YvxVVXIc$$HLNUib1/NxBLVvw2ii2VM1,test2:$$apr1$$WJ59RfPU$$pfxZiefopRcbWztoUpCR31"
      - "traefik.http.services.victorialogs.loadbalancer.server.port=9428"
      - "com.docker.victorialogs=True"
    networks:
      - vlogs
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://victorialogs:9428/health"]
      interval: 1s
      timeout: 1s
      retries: 10

  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    ports:
      - '127.0.0.1:8428:8428'
    command:
      - -storageDataPath=/vmsingle
      - -promscrape.config=/promscrape.yml
      - -loggerFormat=json
    volumes:
      - victorialogs-vector-docker-vm:/vmsingle
      - ./victoriametrics/scrape.yml:/promscrape.yml
    labels:
      com.docker.victorialogs: "True"
    networks:
      - vlogs
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://victoriametrics:8428/health"]
      interval: 1s
      timeout: 1s
      retries: 10

  nginx:
    image: nginx
    ports: [ "127.0.0.1:8082:80" ]
    labels:
      com.docker.victorialogs: "True"
    networks:
      - vlogs

  postgres:
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - vlogs

  rabbitmq:
    image: rabbitmq:3.12.14-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./logs/:/var/log/rabbitmq
    networks:
      - vlogs

volumes:
  victorialogs-vector-docker-vl:
  victorialogs-vector-docker-vm:
  grafana_data:

networks:
  vlogs:
