apiVersion: 1

datasources:
  - name: VictoriaMetrics-test
    type: prometheus
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://victoriametrics:8428
    basicAuth: false
    # isDefault: true
    jsonData:
      httpMethod: GET
    version: 1
    editable: true
  - name: VictoriaLogs
    type: victorialogs-datasource
    access: proxy
    url: http://victorialogs:9428
    # isDefault: true
  - name: VictoriaMetrics
    type: victoriametrics-datasource
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
